name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - run: rustup update stable

      - run: rustup default stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: |
          echo "DEEPINFRA_KEY=${{ secrets.DEEPINFRA_KEY }}" > test.env
          echo "GOOGLE_KEY=${{ secrets.GOOGLE_KEY }}" >> test.env
          echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> test.env

      - run: cargo test --all-features

      - name: Cleanup before Post Run
        run: rm test.env
